name: Flying Delta
on: [push]
env:
    BUILDKITE_API_ACCESS_TOKEN:  ${{ secrets.TRIGGER_BK_BUILD_TOKEN }} 

jobs:
  Fly-Delta-JS:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger a Buildkite Build
        uses: "buildkite/trigger-pipeline-action"
        env:
          PIPELINE: "jamessammut-dot-corp/example-groups"
          BRANCH: "master"
          COMMIT: "HEAD"
          MESSAGE: ":buildkite::github: 🚀🚀 Triggered from GHA: ${{ github.event.head_commit.message }}"
          
