name: Flying Delta
on: [push]
env:
    BUILDKITE_API_ACCESS_TOKEN: ${{ secrets.TRIGGER_BK_BUILD_TOKEN }} 

jobs:
  Fly-Delta:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger a Buildkite Build
        uses: "buildkite/trigger-pipeline-action@v1.3.0"
        env:
          PIPELINE: "lzrbktest/more-pipelines-tests"
          BRANCH: master
          COMMIT: HEAD
          MESSAGE:  ":buildkite:💛💚💙💜 :github: 💛💚💙💜 Triggered from GHA: ${{ github.event.head_commit.message }}  "  
      - name: Trigger a Buildkite Build
        uses: "buildkite/trigger-pipeline-action@v1.3.0"
        env:
          PIPELINE: "lzrbktest/trigger-from-gha-demo"
          BRANCH: ${{ github.ref }}
          COMMIT: ${{ github.sha }}
          MESSAGE:  ":buildkite::github: 🚀🚀🚀 Triggered from GHA: ${{ github.event.head_commit.message }}  "
