name: Flying Delta
on: [push]
env:
    BUILDKITE_API_ACCESS_TOKEN:  ${{ secrets.TRIGGER_BK_BUILD_TOKEN }} 

jobs:
  Fly-Delta-JS:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger a Buildkite Build
        uses: "buildkite/trigger-pipeline-action@65e57ec145f921041570e3eb3e8cc16a19facf3f"
        env:
          PIPELINE: "jamessammut-dot-corp/example-groups"
          BRANCH: "master"
          COMMIT: "HEAD"
          MESSAGE: ":buildkite::github: 🚀🚀 Triggered from GHA: ${{ github.event.head_commit.message }}"
          
on: [delete]          
jobs:
  Fly-Delta-JS:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger a Buildkite Build
        uses: "buildkite/trigger-pipeline-action@v1.4.0"
        env:
          PIPELINE: "jamessammut-dot-corp/example-groups"
          BRANCH: "master"
          COMMIT: "HEAD"
          MESSAGE:  ":buildkite::github: 🚀🚀 Triggered from GHA Delete: ${{ github.event.head_commit.message }}"
          
