name: Flying Delta
on: [push]
jobs:
  Fly-Delta:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger a Buildkite Build
        uses: "buildkite/trigger-pipeline-action@v1.3.0"
        env:
          BUILDKITE_API_ACCESS_TOKEN: ${{ secrets.TRIGGER_BK_BUILD_TOKEN }} 
          PIPELINE: "lzrbktest/more-pipelines-tests"
          BRANCH: master
          COMMIT: HEAD
          MESSAGE:  ":buildkite:💛💚💙💜 :github: 💛💚💙💜  "
