name: Flying Delta
on: [delete]   
env:
    BUILDKITE_API_ACCESS_TOKEN:  ${{ secrets.TRIGGER_BK_BUILD_TOKEN }} 

jobs:
  Fly-Delta-JS:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger a Buildkite Build from a delete event
        uses: "buildkite/trigger-pipeline-action@v1.4.0"
        env:
          PIPELINE: "jamessammut-dot-corp/example-groups"
          BRANCH: "master"
          COMMIT: "HEAD"
          MESSAGE:  ":buildkite::github: 🚀🚀 Triggered from GHA delete event: ${{ github.event.head_commit.message }}"
          
