name: GHA Triggers BK Builds
run-name: ${{ github.actor }} is testing out GitHub Actions triggering BK Pipelines 🚀
on: [push]
jobs:
  Trigger-BK:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - name: Trigger a Buildkite Build
        uses: "buildkite/trigger-pipeline-action@v1.3.0"
        env:
          BUILDKITE_API_ACCESS_TOKEN: ${{ secrets.TRIGGER_BK_BUILD_TOKEN }} 
          PIPELINE: "lzrbktest/trigger-from-gha-demo"
          BRANCH: main
          COMMIT: ${{ github.sha }}
          MESSAGE:  ":buildkite: :github: 🚀🚀🚀 Triggered from GHA: ${{ github.event.head_commit.message }} "

