name: GHA Triggers BK Builds
run-name: ${{ github.actor }} is testing out GitHub Actions triggering BK 🚀
on: [push]
jobs:
  Trigger-BK:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - name: Trigger a Buildkite Build
        uses: "buildkite/trigger-pipeline-action@v1.2.0"
        env:
          BUILDKITE_API_ACCESS_TOKEN: ${{ secrets.BUILDKITE_API_ACCESS_TOKEN }}
          PIPELINE: "lizette-buildkite-test/buildkite-exercises"
          BRANCH: "main"
